name: Test changed files in pull request to Main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CI: true
  NODE_VERSION: 20.12.2

jobs:
  type_check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Running type check to verify any problem with the types
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
      - run: |
          yarn install --frozen-lockfile
          yarn type-check

  linter:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: type_check
    steps:
      - uses: actions/checkout@v4
      - name: Running linters to keep code formatted
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
      - run: |
          yarn install --frozen-lockfile
          yarn lint

  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: linter

    steps:
      - uses: actions/checkout@v4
      - name: Running tests to verify the code
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
      - run: |
          yarn install --frozen-lockfile
          cp .env.sample .env
          yarn test:ci

  cypress-run:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: tests

    env:
      VITE_MARVEL_API_KEY: ${{ secrets.VITE_MARVEL_API_KEY }}
      VITE_MARVEL_API_URL: ${{ secrets.VITE_MARVEL_API_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
      - run: yarn install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: "http://localhost:5173"
          build: yarn build
          start: npx vite --host
          wait-on-timeout: 60
