name: Test changed files in pull request to Main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CI: true
  NODE_VERSION: 20.14.0

jobs:
  type_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Running type check to verify any problem with the types
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
      - run: |
          yarn install --frozen-lockfile
          yarn type-check

  linter:
    runs-on: ubuntu-latest
    needs: type_check

    steps:
      - uses: actions/checkout@v4
      - name: Running linters to keep code formatted
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
      - run: |
          yarn install --frozen-lockfile
          yarn lint
